//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSurvey1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int Class_ID { get; set; }
        public string Class_name { get; set; }
        public bool Class_status { get; set; }
    
        public virtual Class_user Class_user { get; set; }
    }
}
