//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSurvey1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int exm_ID { get; set; }
        public int survey_ID { get; set; }
        public int user_ID { get; set; }
        public int number_question { get; set; }
        public double total_score { get; set; }
        public System.TimeSpan time_score { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual User User { get; set; }
    }
}
