//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSurvey1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Question_meta = new HashSet<Question_meta>();
        }
    
        public int question_ID { get; set; }
        public string question_Date { get; set; }
        public string question_tile { get; set; }
        public string question_status { get; set; }
        public string question_type { get; set; }
        public int question_resuit { get; set; }
        public int survey_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_meta> Question_meta { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
